// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpr23A-dNVhnXOLf2tQXki1A54rhnqFA',
    appId: '1:338990588790:web:683cb09f9504847a985057',
    messagingSenderId: '338990588790',
    projectId: 'hedasaathi-723d0',
    authDomain: 'hedasaathi-723d0.firebaseapp.com',
    storageBucket: 'hedasaathi-723d0.appspot.com',
    measurementId: 'G-Z26BPPYRSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalGTIerGZcbhcUsrfSDjLP9tpCQ6vxNo',
    appId: '1:338990588790:android:933b4aad237fe6a2985057',
    messagingSenderId: '338990588790',
    projectId: 'hedasaathi-723d0',
    storageBucket: 'hedasaathi-723d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3fpybvrDZJFlqArMsCRMsbQiauF7MSL8',
    appId: '1:338990588790:ios:bf7e479a0d100367985057',
    messagingSenderId: '338990588790',
    projectId: 'hedasaathi-723d0',
    storageBucket: 'hedasaathi-723d0.appspot.com',
    iosClientId: '338990588790-flvhmvnqkq6t8719a7nqhcnna5m45657.apps.googleusercontent.com',
    iosBundleId: 'com.example.hedaSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3fpybvrDZJFlqArMsCRMsbQiauF7MSL8',
    appId: '1:338990588790:ios:bf7e479a0d100367985057',
    messagingSenderId: '338990588790',
    projectId: 'hedasaathi-723d0',
    storageBucket: 'hedasaathi-723d0.appspot.com',
    iosClientId: '338990588790-flvhmvnqkq6t8719a7nqhcnna5m45657.apps.googleusercontent.com',
    iosBundleId: 'com.example.hedaSaathi',
  );
}
